-- -------------------------------------------------------------------------------------
-- Debt Account Details Provider
-- Description: Detailed analysis of debt records, including interest calculations,
-- payment history, and splits between pre-collection and active collection phases.
-- -------------------------------------------------------------------------------------

SELECT
   MAIN.*,
   CAST(CONCAT(MAIN.`DOC_DATE`, ' - ', TRIM(MAIN.`DOC_NUMBER`)) AS CHAR) AS 'DEBT_IDENTIFIER',
   {-EXTRA_COLUMNS-},
   DOC_TYPE.`NAME` AS 'DOCUMENT_TYPE_NAME',
   CUR.`CURRENCY_CODE`,
   INT_TABLE.`NAME` AS 'INTEREST_TABLE_NAME',

   -- Date range logic for interest calculation
   IFNULL(ACC.`INT_START_DATE`, IFNULL(MAIN.`INT_CUSTOM_START`, DATE_ADD(MAIN.`DUE_DATE`, INTERVAL 1 DAY))) AS 'INTEREST_FROM',
   IFNULL(ACC.`INT_END_DATE`, IFNULL(MAIN.`INT_CUSTOM_END`, IFNULL(ACC.`TERMINATION_DATE`, DATE(NOW())))) AS 'INTEREST_TO',

   -- Summary of payments and balances
   (MAIN.`TOTAL_AMOUNT` + MAIN.`TOTAL_INTEREST` + MAIN.`TOTAL_COSTS`) AS 'GROSS_TOTAL',
   (MAIN.`TOTAL_AMOUNT` - IFNULL(SETTLE_PRE.`PAID_AMOUNT`, 0) - IFNULL(SETTLE_ACTIVE.`PAID_AMOUNT`, 0)) AS 'REMAINING_PRINCIPAL',

   -- Split between Pre-Collection and Active Collection payments
   IFNULL(SETTLE_PRE.`PAID_TOTAL`, 0) AS 'TOTAL_PAID_PRE_COLLECTION',
   IFNULL(SETTLE_ACTIVE.`PAID_TOTAL`, 0) AS 'TOTAL_PAID_DURING_COLLECTION'

FROM `DEBT_RECORDS` AS MAIN
LEFT OUTER JOIN `DOCUMENT_TYPES` AS DOC_TYPE ON (MAIN.`ID_DOC_TYPE` = DOC_TYPE.`ID`)
LEFT OUTER JOIN `CURRENCIES` AS CUR ON (MAIN.`ID_CURRENCY` = CUR.`ID`)
LEFT OUTER JOIN `INTEREST_RATES` AS INT_TABLE ON (MAIN.`ID_INT_TABLE` = INT_TABLE.`ID`)
LEFT OUTER JOIN `ACCOUNT_SETTINGS` AS ACC ON (MAIN.`ID_DEBT` = ACC.`ID_DEBT`)

-- [SUBQUERY: Aggregating payments made BEFORE collection started]
LEFT OUTER JOIN (
    SELECT
        SETTLE.`ID_DEBT`,
        SUM(SETTLE.`AMOUNT`) AS 'PAID_AMOUNT',
        SUM(SETTLE.`INTEREST`) AS 'PAID_INTEREST',
        SUM(SETTLE.`AMOUNT` + SETTLE.`INTEREST`) AS 'PAID_TOTAL'
    FROM `ACCOUNT_SETTLEMENTS` AS SETTLE
    LEFT OUTER JOIN `PAYMENTS` AS PAY ON (SETTLE.`ID_PAYMENT` = PAY.`ID`)
    WHERE (SETTLE.`ID_ATTACHMENT` = {-:PARAM_ATTACHMENT_ID-})
      AND (PAY.`IS_PRE_COLLECTION` = 1)
    GROUP BY SETTLE.`ID_DEBT`
) AS SETTLE_PRE ON (MAIN.`ID_DEBT` = SETTLE_PRE.`ID_DEBT`)

-- [SUBQUERY: Aggregating payments made DURING active collection]
LEFT OUTER JOIN (
    SELECT
        SETTLE.`ID_DEBT`,
        SUM(SETTLE.`AMOUNT`) AS 'PAID_AMOUNT',
        SUM(SETTLE.`INTEREST`) AS 'PAID_INTEREST',
        SUM(SETTLE.`AMOUNT` + SETTLE.`INTEREST`) AS 'PAID_TOTAL'
    FROM `ACCOUNT_SETTLEMENTS` AS SETTLE
    LEFT OUTER JOIN `PAYMENTS` AS PAY ON (SETTLE.`ID_PAYMENT` = PAY.`ID`)
    WHERE (SETTLE.`ID_ATTACHMENT` = {-:PARAM_ATTACHMENT_ID-})
      AND (PAY.`IS_PRE_COLLECTION` = 0)
    GROUP BY SETTLE.`ID_DEBT`
) AS SETTLE_ACTIVE ON (MAIN.`ID_DEBT` = SETTLE_ACTIVE.`ID_DEBT`)

WHERE (MAIN.`ID_ATTACHMENT` = {-:PARAM_ATTACHMENT_ID-})
ORDER BY MAIN.`DOC_DATE` ASC, MAIN.`DOC_NUMBER` ASC;